### ISSUE TITLE
Add Swagger Annotations

### ISSUE THREAD

**Issue by bshvartsman** [DevOpsS21-Promotions/promotions#67]
**As a** developer
**I need** to add Swagger annotations to the promotions service
**So that** our REST API is documented

**Assumptions:**
* We will be using Flas-RESTPlus as shown in class

**Acceptance Criteria:**
```
Given Swagger annotations have been created
When someone seeks documentation about our promotions service
Then they are able to understand how the service works
```

**Comment by rse4399** [comment]
Done together under promotions#73.
