### ISSUE TITLE
Fix promo code field name on UI

### ISSUE THREAD

**Issue by bshvartsman** [DevOpsS21-Promotions/promotions#85]
**As a** developer
**I need** to change the name for the second "Description" field
**So that** it matches what is listed in the text box ("promo code") when there isn't anything typed in the field (see screenshot)
![image.png](https://images.zenhubusercontent.com/602db233a5942f017a61c8d6/326caebf-d08b-4e24-9925-325bffaa1050)

**Assumptions:**
* this is a bug

**Acceptance Criteria:**
```
Given I am on https://nyu-promotion-service-s21.us-south.cf.appdomain.cloud/
When I look at the field that is underneath "Description" 
Then I will see a field called "Promo Code"
```

**Comment by rse4399** [comment]
Fixed in another pull request
